name: Deploy from ZIP

on:
  workflow_dispatch:  # ← 手動実行トリガー

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Unzip latest archive
        run: |
          unzip yukichi-vote-system.zip -d extracted
          cp -r extracted/yukichi-vote-system/* .

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add .
          git commit -m "🚀 Deploy from ZIP archive" || echo "No changes to commit"
          git push origin main
